#!/usr/bin/env python
import time
# import roslib; roslib.load_manifest('ur_driver')
import rospy
import actionlib
from control_msgs.msg import *
from trajectory_msgs.msg import *


# Create node 
rospy.init_node('mc_gazebo')

robot_client = actionlib.SimpleActionClient('/joint_group_position_controller/follow_joint_trajectory', FollowJointTrajectoryAction)

print("Waiting for server")
robot_client.wait_for_server()
print("Connected to server")

joint_names = ['RL_hip_joint', 'RL_thigh_joint', 'RL_calf_joint', 
               'FL_hip_joint', 'FL_thigh_joint', 'FL_calf_joint',
               'RR_hip_joint', 'RR_thigh_joint', 'RR_calf_joint', 
               'FR_hip_joint', 'FR_thigh_joint', 'FR_calf_joint']

Q0 = [0,0,-0.31, # RL
    0,0,-0.31, # FL
    0,0,-0.31, # RR
    0,0,-0.31] # FR
g = FollowJointTrajectoryGoal()
g.trajectory = JointTrajectory()
g.trajectory.joint_names = joint_names

# Change to different position
g.trajectory.points = [JointTrajectoryPoint(positions=Q0, velocities=[0]*12, time_from_start=rospy.Duration(2.0))]

robot_client.send_goal(g)
robot_client.wait_for_result()
rospy.spin()